<?php

require_once ('class/Mysql.php');

$db = new MySQL('172.16.44.1',"root","ePia6cH3mb", "DB_LPG_GLOBAL");
    $sqlupdate     = "Update SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER,DB_LPG_GLOBAL.LPG_ALL_CUSTOMER  SET
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.NAME_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.NAME_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.NAME2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.NAME2_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ADDRESS1_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ADDRESS1_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ADDRESS2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ADDRESS2_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ZIP_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ZIP_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.CITY_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.CITY_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.TEL_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.TEL_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.MAIL_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.MAIL_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.COUNTRY_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.COUNTRY_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.PASSWORD_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.PASSWORD_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.TYPE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.TYPE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.STRUCTURE_CUST	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.STRUCTURE_CUST	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.JOB_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.JOB_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.WEBSITE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.WEBSITE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LIPOMASSAGE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LIPOMASSAGE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LIPOMODELAGE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LIPOMODELAGE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOLIFT_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOLIFT_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOLIFT2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOLIFT2_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.HML_NIV2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.HML_NIV2_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.H360_NIV2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.H360_NIV2_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOTHERAPIE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOTHERAPIE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.CANCERDUSEIN_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.CANCERDUSEIN_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.KMI_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.KMI_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.KMS_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.KMS_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.KM2I_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.KM2I_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.KM2S_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.KM2S_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOLAB_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOLAB_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.INTEGRAL_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.INTEGRAL_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOLAB_B_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOLAB_B_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.INTEGRAL_B_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.INTEGRAL_B_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ERGODRIVE_I_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ERGODRIVE_I_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.MYLPGP_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.MYLPGP_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LIFT_M6	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LIFT_M6	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LIPO_M6	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LIPO_M6	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LIFT_6	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LIFT_6	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.OLD_CELLU_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.OLD_CELLU_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.HUBER_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.HUBER_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.SPINEFORCE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.SPINEFORCE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.HML_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.HML_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.H360_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.H360_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.TYPES_HML_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.TYPES_HML_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.E6_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.E6_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.R6_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.R6_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.MOBILIFT_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.MOBILIFT_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.MOBILIFT_PHYSIO_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.MOBILIFT_PHYSIO_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.WELLBOX_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.WELLBOX_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.COSMETIC_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.COSMETIC_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOSPA_CORNER_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOSPA_CORNER_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOSPA_FULL_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOSPA_FULL_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ENDERMOSPA_MEDI_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ENDERMOSPA_MEDI_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.CERTIFIED_QUALITY_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.CERTIFIED_QUALITY_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.MVF_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.MVF_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ACTIVELIFE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ACTIVELIFE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.FORMATION_PRO_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.FORMATION_PRO_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.CERTIFIED_QUALITY_2011_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.CERTIFIED_QUALITY_2011_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LATITUDE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LATITUDE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LONGITUDE_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LONGITUDE_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.HIDDEN_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.HIDDEN_CUS	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LOGINDST_CUS = DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LOGINDST_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.EMAIL_TABLET	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.EMAIL_TABLET	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ACCES_TABLET	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ACCES_TABLET	,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.REF_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.REF_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LISTE_FORMATIONS_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LISTE_FORMATIONS_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ACTIF_SITES_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ACTIF_SITES_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LISTE_FORMATIONS2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LISTE_FORMATIONS2_CUS,
SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.LISTE_APPAREILS2_CUS	=	DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.LISTE_APPAREILS2_CUS
WHERE SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.COUNTRY_CUS = DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.COUNTRY_CUS AND SL_TRACKING_SEARCH.LPG_ALL_CUSTOMER.ID_CUS= DB_LPG_GLOBAL.LPG_ALL_CUSTOMER.ID_CUS; ";
  
    $req = $db->query($sqlupdate);
    
       $db->close();
       
       
//STOCKER VISITE DE LA PAGE
//$date = new DateTime(); //this returns the current date time
//$result = $date->format('Y-m-d-H-i-s');
//$file = '/var/www/vhosts/lpgsystems.com/www/webserv.lpgsystems.com/script-cron/files/scriptUpdate' . $result . '.txt';
//$info = "transfert date de fin de script :";
//
//file_put_contents($file, $info);
